### ISSUE TITLE
Add support for plain object

### ISSUE THREAD

**Issue by r-Larch** [r-Larch/OpenAi.JsonSchema#1]
Type: List<object[]>

**System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'type')
Actual value was System.Object.
   at OpenAi.JsonSchema.Generator.DefaultValueSchemaBuilder.BuildSchema(JsonType info, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.DefaultSchemaBuilder.BuildSchema(JsonType type, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.Abstractions.SchemaBuildContext.Generate(JsonType type)
   at OpenAi.JsonSchema.Generator.DefaultArraySchemaBuilder.BuildSchema(JsonType type, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.DefaultSchemaBuilder.BuildSchema(JsonType type, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.Abstractions.SchemaBuildContext.Generate(JsonType type)
   at OpenAi.JsonSchema.Generator.DefaultArraySchemaBuilder.BuildSchema(JsonType type, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.DefaultSchemaBuilder.BuildSchema(JsonType type, SchemaBuildContext context)
   at OpenAi.JsonSchema.Generator.DefaultSchemaGenerator.Generate(Type type, JsonSchemaOptions options)
   at OpenAi.JsonSchema.Generator.DefaultSchemaGenerator.Generate[T](JsonSchemaOptions options)**

**Comment by r-Larch** [comment]
This is now possible using the fluent API
